name: momolab

services:
  postgres:
    image: postgres:16
    container_name: momolab_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: momo
      POSTGRES_PASSWORD: "3214"
      POSTGRES_DB: momolab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - momolab_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: momolab/fastapi:1.0
    container_name: momolab_fastapi
    environment:
      DATABASE_URL: "postgresql+psycopg://momo:3214@postgres:5432/momolab"
    ports:
      - "8080:8080"
    networks:
      - momolab_network

volumes:
  postgres_data:

networks:
  momolab_network:
    driver: bridge